language: node_js
node_js:
- '5'

deploy:
  provider: npm
  email: berezin.mvdev@yahoo.com
  api_key:
    secure: Nb8hfYG3V1lm+sHU9HA4unrW9Ru8qHwq2Dm2C38tcA4G5Zgg8QDrAGJNaeztdqc3VfUrY8mo12dvlLnHIPokz7pBVd6afpHO15HdHCMC+O6Sm1Fg85VnpqhjzemhSGFx0UI026fIWkqvixzuds/gljYy+vxYCNEkWyCv6CTo3HfEDYUb70ynmwpOaK2vgSm9Qu8oJ5bi9IswP30H6/wKyXBCzuVb0L10GGonOG+2cjUhemPnMJFumbKkzXi6KUEzxOsT93jzmwCJEjWUvTDbLZEAsFOh5bFIVIcHvhvflywgycthu+CFu85cLLsvxujAIWy/RFjn0ETOzboRLVseDJURTVYkZddk5CVd73i2ZgdFTyJzHPDfCbmmrGWVFqz0h8cz4s95OEVBN76fuvZ55PPxot+SVP1ubfDX+P1W86uQot5vq8JFkRtmmd45uZ5bZ2giHiOPy4qYnTqzOGxMYunU34b0z3TS8ncGjupG8nPjqQf2ax0j9ZG27xZEffxWKlnHOWSYrbn/Y6JmwASQ41yakWTyItohooAHB/GAxd+U11fdFEfvu8lkZsZO8nTGPep3XN3PHWPCRPquIW3aUq5w6gMgRQsLv/Y32+KwAc9HtDnXI27NOq0scgYXIKKGBF0jYky2PbwhbRwfTMF8eArp3LoVT2EXZWClQI4U6x4=
